export const SECTIONS = [
  { id: 'workshop', name: 'The Workshop', subtitle: 'Tools & Making', icon: '⚒️', color: '#f59e0b', description: 'Forge, build, and craft with your hands' },
  { id: 'wilds', name: 'The Wilds', subtitle: 'Bush & Field', icon: '🌲', color: '#22c55e', description: 'Explore the untamed lands beyond' },
  { id: 'shire', name: 'The Shire', subtitle: 'Land Systems', icon: '🌾', color: '#eab308', description: 'Tend the gardens and growing things' },
  { id: 'hearth', name: 'The Hearth', subtitle: 'Home & Kitchen', icon: '🔥', color: '#ef4444', description: 'Master the arts of fire and food' },
  { id: 'library', name: 'The Library', subtitle: 'Words & Maps', icon: '📜', color: '#6366f1', description: 'Seek knowledge in ancient tomes' },
] as const

export const SUBSECTIONS: Record<string, readonly { id: string; name: string; icon: string; description: string }[]> = {
  workshop: [
    { id: 'woodworking', name: 'Woodworking', icon: '🪵', description: 'Shape timber into useful things' },
    { id: 'metalwork', name: 'Metalwork', icon: '⚙️', description: 'Forge and shape metal' },
    { id: 'leathercraft', name: 'Leathercraft', icon: '🧵', description: 'Work with hides and leather' },
    { id: 'electronics', name: 'Electronics', icon: '💡', description: 'Circuits, wires, and power' },
    { id: 'general-making', name: 'General Making', icon: '🔧', description: 'Other workshop crafts' },
  ],
  wilds: [
    { id: 'bushcraft', name: 'Bushcraft', icon: '🏕️', description: 'Survival skills in the wild' },
    { id: 'tracking', name: 'Tracking', icon: '🐾', description: 'Follow trails and signs' },
    { id: 'foraging', name: 'Foraging', icon: '🍄', description: 'Find food in nature' },
    { id: 'wildlife', name: 'Wildlife', icon: '🦊', description: 'Observe and understand animals' },
    { id: 'navigation', name: 'Navigation', icon: '🧭', description: 'Find your way in wild places' },
  ],
  shire: [
    { id: 'gardening', name: 'Gardening', icon: '🌱', description: 'Grow plants and vegetables' },
    { id: 'composting', name: 'Composting', icon: '🍂', description: 'Turn waste into soil' },
    { id: 'orcharding', name: 'Orcharding', icon: '🍎', description: 'Tend fruit trees and vines' },
    { id: 'beekeeping', name: 'Beekeeping', icon: '🐝', description: 'Keep bees and harvest honey' },
    { id: 'land-management', name: 'Land Management', icon: '🚜', description: 'Care for the broader land' },
  ],
  hearth: [
    { id: 'cooking', name: 'Cooking', icon: '🍳', description: 'Prepare meals and dishes' },
    { id: 'baking', name: 'Baking', icon: '🍞', description: 'Breads, pastries, and sweets' },
    { id: 'preserving', name: 'Preserving', icon: '🫙', description: 'Store food for later' },
    { id: 'fermentation', name: 'Fermentation', icon: '🧪', description: 'Pickles, drinks, and cultures' },
    { id: 'home-keeping', name: 'Home Keeping', icon: '🏠', description: 'Maintain and organize the home' },
  ],
  library: [
    { id: 'reading', name: 'Reading', icon: '📚', description: 'Books, articles, and texts' },
    { id: 'writing', name: 'Writing', icon: '✍️', description: 'Record thoughts and stories' },
    { id: 'cartography', name: 'Cartography', icon: '🗺️', description: 'Make and read maps' },
    { id: 'research', name: 'Research', icon: '🔍', description: 'Investigate and discover' },
    { id: 'languages', name: 'Languages', icon: '🗣️', description: 'Learn tongues old and new' },
    { id: 'curated-reading', name: 'Curated Reading', icon: '📖', description: 'Classic tomes every adventurer should know' },
  ],
} as const

export const TIERS = [
  { id: 'wanderer', name: 'Wanderer', rank: 1, description: 'Exploration with capture', xp: 10, stars: 1 },
  { id: 'traveller', name: 'Traveller', rank: 2, description: 'Reliable completion', xp: 25, stars: 2 },
  { id: 'wayfarer', name: 'Wayfarer', rank: 3, description: 'Multi-step competence', xp: 50, stars: 3 },
  { id: 'pathfinder', name: 'Pathfinder', rank: 4, description: 'Complex responsibility', xp: 100, stars: 4 },
  { id: 'guide', name: 'Guide', rank: 5, description: 'Generative leadership', xp: 200, stars: 5 },
] as const

export const TYPES = [
  { id: 'observation', name: 'Observation', icon: '👁️', prompts: ['What did you notice?', 'What pattern did you see?', 'What question do you have now?'] },
  { id: 'practice', name: 'Practice', icon: '🎯', prompts: ['What did you practice?', 'What improved?', 'What will you try next?'] },
  { id: 'experiment', name: 'Experiment', icon: '⚗️', prompts: ['What did you change?', 'What happened?', 'Why do you think?'] },
  { id: 'build', name: 'Build', icon: '🔨', prompts: ['What did you build?', 'What tools and materials?', 'What worked or failed?'] },
  { id: 'project', name: 'Project', icon: '📋', prompts: ['What was the goal?', 'What progress today?', 'What is the next step?'] },
  { id: 'expedition', name: 'Expedition', icon: '🧭', prompts: ['Where did you go?', 'What did you find?', 'What next time?'] },
  { id: 'service', name: 'Service', icon: '🤝', prompts: ['Who did you help?', 'What responsibility?', 'What standard did you aim for?'] },
  { id: 'teaching', name: 'Teaching', icon: '📖', prompts: ['What did you teach?', 'How did they understand it?', 'What would you improve?'] },
] as const

export const AVATAR_STAGES = [
  { minLevel: 1, name: 'Young Hobbit', description: 'Just beginning the journey' },
  { minLevel: 3, name: 'Eager Wanderer', description: 'Finding your feet on the road' },
  { minLevel: 5, name: 'Seasoned Traveller', description: 'The path becomes familiar' },
  { minLevel: 8, name: 'Bold Wayfarer', description: 'No trail is too long' },
  { minLevel: 12, name: 'Wise Pathfinder', description: 'Others follow your lead' },
  { minLevel: 18, name: 'Legendary Guide', description: 'Master of all realms' },
] as const

export const QUESTS = [
  { id: 'shield', title: 'Forge a Shield', description: 'Craft a wooden shield with a proper grip', instructions: '1. Choose a flat piece of wood roughly 40cm across.\n2. Cut or sand it into a round or kite shape.\n3. Attach a handle on the back using screws or a wood strip.\n4. Sand the edges smooth so there are no splinters.\n5. Paint or decorate with a personal emblem.', section: 'workshop', subsection: 'woodworking', type: 'build', tier: 'traveller', image: 'shield' },
  { id: 'sword', title: 'Forge a Sword', description: 'Shape a blade and wrap the grip with cord', instructions: '1. Find a straight piece of timber about 60–70cm long.\n2. Mark out a blade shape and a handle section.\n3. Saw and sand the blade to a flat, tapered profile.\n4. Shape a cross-guard from a small block and attach it.\n5. Wrap the handle tightly with cord or leather strip.\n6. Sand everything smooth and apply oil or paint.', section: 'workshop', subsection: 'woodworking', type: 'build', tier: 'traveller', image: 'sword' },
  { id: 'hookboard', title: 'The Hook Board', description: 'Build a board with hooks for your tools', instructions: '1. Choose a sturdy board about 50cm wide.\n2. Sand it smooth and mark where each hook will go.\n3. Screw in hooks or pegs at even spacing.\n4. Attach mounting hardware to the back.\n5. Hang it on the workshop wall and organise your tools.', section: 'workshop', subsection: 'woodworking', type: 'build', tier: 'wanderer', image: 'hookboard' },
  { id: 'joints', title: 'Test of Joints', description: 'Which is strongest—screw, nail, or glue?', instructions: '1. Cut six identical pairs of small wood pieces.\n2. Join two pairs with screws, two with nails, and two with wood glue.\n3. Let any glue dry fully before testing.\n4. Test each joint by pulling, twisting, and bending.\n5. Record which held best and which failed first.\n6. Write down why you think the winner was strongest.', section: 'workshop', subsection: 'woodworking', type: 'experiment', tier: 'wayfarer', image: 'joints' },
  { id: 'safety', title: 'The Rules of Steel', description: 'Learn and record the safety rules of tools', instructions: '1. Pick three tools you use or want to learn (e.g. saw, drill, chisel).\n2. Research or ask an adult about the safety rules for each.\n3. Write or draw the rules clearly on a card or poster.\n4. Include what protective gear is needed for each tool.\n5. Display the rules in your workshop where you can see them.', section: 'workshop', subsection: 'general-making', type: 'observation', tier: 'wanderer', image: 'safety' },
  { id: 'birdwatch', title: 'Bird Watch', description: 'Find and identify three different birds', instructions: '1. Choose a spot outdoors where you can sit quietly.\n2. Bring a notebook and pencil (binoculars if you have them).\n3. Sit still for at least 15 minutes and watch for birds.\n4. Sketch or describe each different bird you see.\n5. Use a field guide or app to identify at least three species.\n6. Note their colours, size, call, and behaviour.', section: 'wilds', subsection: 'wildlife', type: 'observation', tier: 'wanderer', image: 'birdwatch' },
  { id: 'firestart', title: 'Spark to Flame', description: 'Start a fire using natural materials', instructions: '1. Gather tinder (dry grass, bark shavings), kindling (small sticks), and fuel (larger sticks).\n2. Clear a safe fire area on bare ground, away from anything flammable.\n3. Build a small tinder nest and arrange kindling above it.\n4. Use a ferro rod, flint and steel, or friction method to create a spark.\n5. Gently blow on the ember until it catches the tinder.\n6. Feed kindling slowly until you have a stable flame.\n7. Always have water nearby and fully extinguish when done.', section: 'wilds', subsection: 'bushcraft', type: 'practice', tier: 'wayfarer', image: 'firestart' },
  { id: 'bread', title: 'The Daily Bread', description: 'Bake a loaf from scratch', instructions: '1. Mix 500g flour, 7g yeast, 10g salt, and 325ml warm water.\n2. Knead the dough for about 10 minutes until smooth and elastic.\n3. Cover and let it rise in a warm spot for 1 hour (until doubled).\n4. Punch down, shape into a loaf, and place on a baking tray.\n5. Let it rise again for 30 minutes.\n6. Score the top with a knife and bake at 220°C for 25–30 minutes.\n7. It is done when it sounds hollow when you tap the bottom.', section: 'hearth', subsection: 'baking', type: 'build', tier: 'traveller', image: 'bread' },
  { id: 'plant', title: 'Seed to Sprout', description: 'Plant seeds and record their growth', instructions: '1. Choose fast-growing seeds (beans, sunflowers, or radishes work well).\n2. Fill small pots with damp potting soil.\n3. Plant seeds at the depth shown on the packet.\n4. Place in a sunny spot and water gently each day.\n5. Measure and sketch or photograph the growth every few days.\n6. Record the date each seedling breaks the surface.', section: 'shire', subsection: 'gardening', type: 'project', tier: 'traveller', image: 'plant' },
  { id: 'map', title: 'Chart the Land', description: 'Draw a map of your surroundings', instructions: '1. Walk around your area and note landmarks, paths, and features.\n2. Sketch a rough layout on scrap paper while exploring.\n3. Back inside, draw a clean map on good paper.\n4. Add a compass rose showing north.\n5. Include a simple scale and legend for symbols.\n6. Mark important places: home, water, big trees, paths.', section: 'library', subsection: 'cartography', type: 'build', tier: 'wayfarer', image: 'map' },
  // Permaculture quests (child-friendly)
  { id: 'wormworld', title: 'The Worm\'s World', description: 'Dig up a patch of soil and observe the worms that live there', instructions: '1. Choose a damp, shady patch of garden soil.\n2. Use a trowel to carefully dig up a 30cm square, about 15cm deep.\n3. Gently break apart the soil and look for worms.\n4. Count how many you find and note their sizes.\n5. Observe how they move and react to light.\n6. Carefully return all the worms and soil when done.', section: 'shire', subsection: 'composting', type: 'observation', tier: 'wanderer', image: 'wormworld' },
  { id: 'compost', title: 'Compost Treasure', description: 'Start a kitchen scrap compost and record what goes in', instructions: '1. Find or make a small compost container (a bucket with holes, or a corner of the garden).\n2. Start with a layer of dry leaves, straw, or cardboard.\n3. Add kitchen scraps: fruit peels, veggie ends, eggshells, tea bags.\n4. Avoid meat, dairy, and oily food.\n5. Add a handful of dry material on top each time you add scraps.\n6. Keep a log of what you add and the date.', section: 'shire', subsection: 'composting', type: 'build', tier: 'wanderer', image: 'compost' },
  { id: 'mulch', title: 'The Mulch Blanket', description: 'Gather leaves and straw to mulch around your plants', instructions: '1. Collect fallen leaves, straw, grass clippings, or wood chips.\n2. Choose a garden bed or some plants that need mulching.\n3. Pull any weeds from around the base of the plants.\n4. Spread a layer of mulch 5–10cm thick around (not touching) the stems.\n5. Water the area after mulching.\n6. Check back in a week and note how the soil feels underneath.', section: 'shire', subsection: 'gardening', type: 'practice', tier: 'wanderer', image: 'mulch' },
  { id: 'threesisters', title: 'Three Sisters Garden', description: 'Plant corn, beans, and squash together and watch them help each other grow', instructions: '1. Prepare a mound of soil about 30cm high and 60cm across.\n2. Plant 4 corn seeds in the centre of the mound.\n3. When corn is 15cm tall, plant 4 bean seeds around it.\n4. At the same time, plant 2 squash seeds at the edge of the mound.\n5. Water regularly and watch: corn gives beans a pole, beans fix nitrogen, squash shades the soil.\n6. Journal how each plant grows and helps the others.', section: 'shire', subsection: 'gardening', type: 'project', tier: 'traveller', image: 'threesisters' },
  { id: 'herbspiral', title: 'The Herb Spiral', description: 'Build a spiral-shaped herb garden with stones and soil', instructions: '1. Mark a circle about 1.5m across on the ground.\n2. Lay stones in a spiral shape, building up height toward the centre.\n3. Fill the spiral with soil, higher in the middle.\n4. Plant herbs that like dry conditions near the top (rosemary, thyme).\n5. Plant herbs that like moisture near the bottom (parsley, mint).\n6. Water and label each herb.', section: 'shire', subsection: 'gardening', type: 'build', tier: 'traveller', image: 'herbspiral' },
  { id: 'raincatch', title: 'Catch the Rain', description: 'Set up a simple rain collector and measure what you catch', instructions: '1. Find a large clean container (bucket or barrel).\n2. Place it under a roof edge or downpipe where rain runs off.\n3. Mark measurement lines on the inside with a waterproof marker.\n4. After each rain, measure and record how much water you collected.\n5. Track rainfall over at least a week.\n6. Calculate how much water your roof catches per storm.', section: 'shire', subsection: 'land-management', type: 'build', tier: 'traveller', image: 'raincatch' },
  { id: 'bugcensus', title: 'The Bug Census', description: 'Count and identify the insects living in your garden', instructions: '1. Choose a 1m × 1m patch of garden to survey.\n2. Look carefully on leaves, under rocks, in the soil, and on stems.\n3. Catch insects gently in a clear jar to observe them.\n4. Count and sketch or photograph each type you find.\n5. Use a field guide or app to identify as many as you can.\n6. Release all insects where you found them and record your results.', section: 'wilds', subsection: 'wildlife', type: 'observation', tier: 'wanderer', image: 'bugcensus' },
  { id: 'patterns', title: 'Nature\'s Patterns', description: 'Find spirals, branches, and webs in the wild and sketch them', instructions: '1. Head outdoors with a sketchbook and pencil.\n2. Look for spiral patterns (snail shells, fern fronds, flower centres).\n3. Find branching patterns (trees, rivers, leaf veins, lightning).\n4. Search for web or net patterns (spider webs, honeycomb, cracked mud).\n5. Sketch at least one example of each pattern type.\n6. Label each sketch with where you found it.', section: 'wilds', subsection: 'tracking', type: 'observation', tier: 'wanderer', image: 'patterns' },
  { id: 'forage', title: 'The Forage Basket', description: 'Find and identify three safe edible wild plants with a guide', instructions: '1. Go with an experienced adult or use a trusted foraging guide.\n2. Walk slowly through a wild or semi-wild area.\n3. Identify at least three edible plants (e.g. dandelion, clover, wild garlic).\n4. Only pick plants you are 100% sure about — when in doubt, leave it.\n5. Collect a small amount of each into a basket.\n6. Note where each plant was growing and what it looked like.', section: 'wilds', subsection: 'foraging', type: 'expedition', tier: 'traveller', image: 'forage' },
  { id: 'gardentable', title: 'Garden to Table', description: 'Pick something you grew and cook a meal with it', instructions: '1. Harvest something from your garden (herbs, vegetables, or fruit).\n2. Wash everything thoroughly.\n3. Choose a simple recipe that features what you picked.\n4. Prepare and cook the meal (with help if needed).\n5. Serve it and note how it tastes compared to store-bought.\n6. Reflect on the journey from planting to plate.', section: 'hearth', subsection: 'cooking', type: 'practice', tier: 'traveller', image: 'gardentable' },
  // Bushcraft quests (inspired by Bushcraft 101 & SAS Survival Handbook)
  { id: 'featherstick', title: 'The Feather Stick', description: 'Whittle fine curls from a dry stick for fire-starting tinder', instructions: '1. Choose a dry, straight-grained stick about 30cm long and thumb-thick.\n2. Brace the stick firmly against a log or your knee.\n3. Using a sharp knife, push thin shavings downward — leave them attached so they curl like feathers.\n4. Rotate the stick and repeat, building up layers of curls all around.\n5. Aim for at least 10 thin, wispy curls that would catch a spark.\n6. Test your feather stick by touching a flame or spark to the curls.\n7. Always cut away from your body and keep fingers behind the blade.', section: 'wilds', subsection: 'bushcraft', type: 'practice', tier: 'traveller', image: 'featherstick' },
  { id: 'cordagetwist', title: 'The Cordage Twist', description: 'Twist plant fibres into usable rope using the reverse-wrap method', instructions: '1. Gather long, flexible plant fibres — nettle stems, willow bark, or long dry grass work well.\n2. If using nettle or bark, strip the outer fibres and let them dry slightly.\n3. Take a bundle of fibres and fold it unevenly (one side longer) to form two legs.\n4. Pinch the fold point and twist the leg closest to you away from you.\n5. Wrap that twisted leg over the other leg, toward you.\n6. Repeat: twist away, wrap toward. This is the reverse-wrap technique.\n7. Splice in new fibres before a leg runs out by laying them alongside and twisting together.\n8. Aim to make at least 30cm of usable cord and test its strength.', section: 'wilds', subsection: 'bushcraft', type: 'practice', tier: 'traveller', image: 'cordagetwist' },
  { id: 'barkvessel', title: 'Bark Vessel', description: 'Fold a container from bark using cuts, folds, and cordage', instructions: '1. Find a piece of flexible bark about 30cm × 20cm — birch or thick eucalyptus bark works well.\n2. Soak the bark in water for 20 minutes to make it pliable.\n3. Score fold lines across the short ends, about 5cm from each edge.\n4. Fold the ends upward to form walls.\n5. Pinch the corners together and pierce small holes with an awl or nail.\n6. Lace the corners shut with cordage, thin wire, or a split twig.\n7. Test your vessel by filling it with water — a well-made bark container will hold water.', section: 'wilds', subsection: 'bushcraft', type: 'build', tier: 'wayfarer', image: 'barkvessel' },
  { id: 'debrishut', title: 'Debris Hut', description: 'Build a one-person shelter from branches and leaf litter', instructions: '1. Find a long, sturdy ridgepole — a fallen branch about twice your height.\n2. Prop one end on a stump or fork about waist height; the other end rests on the ground.\n3. Lean sticks along both sides of the ridgepole like ribs, leaving a body-width gap.\n4. Layer smaller sticks crosswise over the ribs to form a lattice.\n5. Pile leaf litter, bracken, or grass thickly over the lattice — at least 30cm deep.\n6. Stuff the inside floor with dry leaves for insulation.\n7. The shelter should be just big enough for you — small spaces trap body heat.\n8. Crawl inside and check for gaps; patch any holes with more debris.', section: 'wilds', subsection: 'bushcraft', type: 'build', tier: 'wayfarer', image: 'debrishut' },
  { id: 'tarpcamp', title: 'Tarp Camp', description: 'Rig a tarp shelter with ridgelines and knots, then use it', instructions: '1. Choose a sheltered spot between two trees roughly 4m apart.\n2. Tie a ridgeline between the trees at head height using a bowline at one end and a taut-line hitch at the other.\n3. Drape a tarp over the ridgeline so it hangs evenly on both sides.\n4. Stake or tie the four corners using guy-lines and clove hitches.\n5. Adjust the taut-line hitches until the tarp is taut with no sagging.\n6. Set up a sitting area underneath with a ground sheet or log seat.\n7. Spend at least an hour under your shelter — eat a snack, read, or journal.\n8. Before leaving, practise breaking camp: pack the tarp, remove all cordage, and leave no trace.', section: 'wilds', subsection: 'bushcraft', type: 'build', tier: 'pathfinder', image: 'tarpcamp' },
  { id: 'wildknots', title: 'Knots of the Wild', description: 'Learn and demonstrate five essential camp knots', instructions: '1. Gather a length of rope or paracord (at least 1.5m) and a stick or post to practise on.\n2. Learn the bowline — the rescue knot that creates a fixed loop. Practise until you can tie it in under 30 seconds.\n3. Learn the clove hitch — for fastening rope to a post or tree quickly.\n4. Learn the taut-line hitch — an adjustable knot for tensioning guy-lines.\n5. Learn the sheet bend — for joining two ropes of different thickness.\n6. Learn the timber hitch — for dragging logs or bundling sticks.\n7. Tie each knot three times from memory and test it holds under load.\n8. Record each knot with a sketch or photo showing the finished result.', section: 'wilds', subsection: 'bushcraft', type: 'practice', tier: 'traveller', image: 'wildknots' },
  { id: 'waterquest', title: 'The Water Quest', description: 'Find, collect, and purify water from a natural source', instructions: '1. With an adult, locate a natural water source — a stream, spring, or rainwater collection.\n2. Observe the water: is it clear or murky? Is it flowing or still? Flowing water is generally safer.\n3. Collect water in a clean container.\n4. Method A — Boiling: bring the water to a rolling boil for at least 1 minute.\n5. Method B — DIY filter: layer charcoal, sand, and gravel in a cut bottle; pour water through slowly.\n6. If using a filter, still boil the filtered water before tasting.\n7. Compare the look and smell of raw vs. purified water.\n8. Never drink wild water without purifying it first. Safety is the whole point of this quest.', section: 'wilds', subsection: 'bushcraft', type: 'experiment', tier: 'wayfarer', image: 'waterquest' },
  { id: 'trackcast', title: 'Track Cast', description: 'Find an animal track and make a plaster cast of it', instructions: '1. Search for clear animal tracks in mud, soft soil, or wet sand — after rain is ideal.\n2. Identify the track if you can: count the toes, measure the size, note claw marks.\n3. Clear any loose debris from inside the track without disturbing the print.\n4. Press a ring of cardboard or a cut plastic bottle into the soil around the track to form a wall.\n5. Mix plaster of Paris to a thick-cream consistency and pour it gently into the track.\n6. Wait 20–30 minutes for the plaster to set fully.\n7. Carefully lift the cast and brush off loose soil.\n8. Label the back with the date, location, and your best identification of the animal.', section: 'wilds', subsection: 'tracking', type: 'build', tier: 'traveller', image: 'trackcast' },
  { id: 'naturalnavigator', title: 'Natural Navigator', description: 'Find north three ways without a compass', instructions: '1. Method 1 — Shadow stick: push a straight stick into the ground in sunlight. Mark the tip of its shadow. Wait 15 minutes and mark the new shadow tip. The line between marks runs roughly east–west; north is at right angles.\n2. Method 2 — Watch method: point the hour hand of an analogue watch at the sun. The midpoint between the hour hand and 12 o\'clock points roughly north (south in the southern hemisphere).\n3. Method 3 — Natural signs: observe moss (often thicker on the shaded side of trees), prevailing wind direction on shaped trees, or the sun\'s arc (rises east, sets west).\n4. Compare all three methods: do they agree?\n5. Check your results with a real compass and note how close you were.\n6. Record which method you found most reliable and why.', section: 'wilds', subsection: 'navigation', type: 'practice', tier: 'traveller', image: 'naturalnavigator' },
  { id: 'signalrescue', title: 'Signal & Rescue', description: 'Learn emergency signals: fire layout, ground signs, and whistle code', instructions: '1. Learn the international distress signal: three of anything — three fires, three whistle blasts, three flashes.\n2. Lay out (but do not light) a signal fire triangle: three fire spots in a triangle, each about 3m apart, with kindling and fuel ready.\n3. Learn three ground-to-air signals: V means "need assistance", X means "need medical help", → (arrow) means "travelling this direction".\n4. Mark one ground signal large enough to see from above (at least 3m long) using sticks, rocks, or clothing.\n5. Practise the whistle code: three short blasts, pause, repeat — the universal call for help.\n6. Learn the response signal: two blasts means "message received, help coming".\n7. Discuss with your group: when would you use each method, and why might one work better than another?', section: 'wilds', subsection: 'navigation', type: 'practice', tier: 'wayfarer', image: 'signalrescue' },
  // Curated Reading quests
  { id: 'read-hobbit', title: 'There and Back Again', description: 'Read The Hobbit by J.R.R. Tolkien and journal your journey with Bilbo', instructions: '1. Obtain a copy of The Hobbit by J.R.R. Tolkien.\n2. Read the book at your own pace — aim for at least one chapter per sitting.\n3. After every few chapters, write a short journal entry: what happened, what surprised you, and what you would have done differently.\n4. Sketch a map of Bilbo\'s journey as you read, adding landmarks as they appear.\n5. When finished, write a final reflection: what did Bilbo learn about himself, and what did you learn from his story?\n6. Choose your favourite passage and copy it out by hand in your best writing.', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'traveller', image: 'read-hobbit' },
  { id: 'read-hatchet', title: 'The Hatchet Trial', description: 'Read Hatchet by Gary Paulsen and test Brian\'s survival ideas', instructions: '1. Obtain a copy of Hatchet by Gary Paulsen.\n2. Read the book from start to finish.\n3. As you read, keep a list of every survival skill Brian uses or learns.\n4. Pick three of Brian\'s techniques (e.g. fire-starting, shelter, finding food) and research whether his methods would actually work.\n5. If safe to do so, try one of the simpler techniques yourself (with adult supervision).\n6. Write a reflection: what was Brian\'s most important survival skill, and why?', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'traveller', image: 'read-hatchet' },
  { id: 'read-mysideofmountain', title: 'My Side of the Mountain', description: 'Read Jean Craighead George\'s classic about a boy living wild in the Catskills', instructions: '1. Obtain a copy of My Side of the Mountain by Jean Craighead George.\n2. Read the book, paying close attention to how Sam builds his life in the wilderness.\n3. Keep a nature journal alongside: sketch any plants, animals, or shelters Sam describes.\n4. Research one real skill from the book — making a fishing hook from a thorn, hollowing a tree, or tanning a hide.\n5. Try foraging for or identifying one wild plant Sam mentions (with a field guide and adult help).\n6. Write a reflection: could you live as Sam did? What would be the hardest part?', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'wayfarer', image: 'read-mysideofmountain' },
  { id: 'read-swissrobinson', title: 'The Swiss Family', description: 'Read The Swiss Family Robinson and catalogue the family\'s inventions', instructions: '1. Obtain a copy of The Swiss Family Robinson by Johann David Wyss.\n2. Read the book, noting every shelter, tool, or contraption the family builds.\n3. Create an illustrated catalogue of at least six of their inventions, with a sketch and description of each.\n4. Choose one invention and design your own improved version on paper — label the materials and explain how it works.\n5. Reflect on which of their creations was most clever and which was most far-fetched.\n6. Write a short entry about what the family did well and what you would have done differently.', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'wayfarer', image: 'read-swissrobinson' },
  { id: 'read-bushcraft101', title: 'The Bushcrafter\'s Manual', description: 'Study Bushcraft 101 by Dave Canterbury and practise five core skills', instructions: '1. Obtain a copy of Bushcraft 101 by Dave Canterbury.\n2. Read through the book, focusing on the five Cs of survivability: cutting, combustion, cover, containers, and cordage.\n3. For each of the five Cs, write a summary of the key principles in your own words.\n4. Choose one skill from each C and practise it hands-on (with supervision where needed).\n5. Document each practice session with notes and photos.\n6. Write a final reflection on which of the five Cs you found most challenging and why.', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'pathfinder', image: 'read-bushcraft101' },
  { id: 'read-robinson', title: 'Castaway\'s Chronicle', description: 'Read Robinson Crusoe by Daniel Defoe and map his island world', instructions: '1. Obtain a copy of Robinson Crusoe by Daniel Defoe.\n2. Read the book, noting every resource Crusoe discovers and every structure he builds.\n3. Draw a detailed map of Crusoe\'s island based on the descriptions in the text, marking his fortress, farm, and key locations.\n4. Create a timeline of his years on the island, marking the major milestones.\n5. Compare Crusoe\'s methods to modern survival techniques — what would an expert do differently today?\n6. Write a reflection: what kept Crusoe going through all those years alone?', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'wayfarer', image: 'read-robinson' },
  { id: 'read-boymechanic', title: 'The Boy Mechanic', description: 'Study projects from The Boy Mechanic and build one', instructions: '1. Obtain a copy of The Boy Mechanic (originally published by Popular Mechanics, various editions available).\n2. Browse through the projects and pick five that interest you most.\n3. For each, write a short note on what materials and tools are needed and whether you could realistically build it.\n4. Choose one project and build it, following the instructions and adapting with modern materials where needed.\n5. Document your build with photos and notes on what worked and what you had to change.\n6. Present your finished project and explain what you learned about the craft.', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'pathfinder', image: 'read-boymechanic' },
  { id: 'read-tracker', title: 'The Tracker\'s Way', description: 'Read The Tracker by Tom Brown Jr. and practise an awareness exercise', instructions: '1. Obtain a copy of The Tracker by Tom Brown Jr.\n2. Read the book, noting the awareness and observation techniques Stalking Wolf teaches.\n3. Choose one awareness exercise from the book — such as wide-angle vision, silent walking, or sit-spot observation.\n4. Practise your chosen exercise outdoors for at least 20 minutes on three separate days.\n5. Keep a journal of what you notice each session — sounds, movements, tracks, weather shifts.\n6. Write a reflection: how did slowing down and paying attention change what you experienced?', section: 'library', subsection: 'curated-reading', type: 'project', tier: 'traveller', image: 'read-tracker' },
  { id: 'electromagnet', title: 'The Electromagnet', description: 'Wind a coil of wire around an iron nail and harness the power of electricity and magnetism', instructions: '1. Gather materials: a large iron nail (10–15cm), thin insulated copper wire (at least 1m), a D-cell battery, and some small paperclips or staples.\n2. Leave about 15cm of wire free at one end, then start wrapping the wire tightly around the nail in neat, close coils from one end to the other.\n3. Keep wrapping in the same direction — do not change the winding direction. The more turns, the stronger the magnet.\n4. Leave another 15cm of wire free at the other end and cut the wire.\n5. Use sandpaper or scissors to strip about 2cm of insulation from both wire ends to expose the bare copper.\n6. Touch one bare wire end to the positive terminal of the battery and the other to the negative terminal.\n7. While the wires are connected, bring the nail tip near the paperclips — they should be attracted and stick to the nail.\n8. Disconnect the wires and observe the paperclips falling off — the magnetism only works when current flows.\n9. Experiment: try different numbers of coil turns or adding a second battery in series. Record how many paperclips your electromagnet can lift each time.\n10. Safety: the wire and nail may get warm — do not leave the circuit connected for more than 30 seconds at a time, and never use mains electricity.', section: 'workshop', subsection: 'electronics', type: 'build', tier: 'traveller', image: 'electromagnet' },
] as const

// Types
export type Section = typeof SECTIONS[number]
export type Subsection = { id: string; name: string; icon: string; description: string }
export type Tier = typeof TIERS[number]
export type QuestType = typeof TYPES[number]
export type Quest = typeof QUESTS[number]

export interface Entry {
  id: string
  timestamp: string
  title: string
  section: string
  subsection: string
  type: string
  tier: string
  questId?: string
  image: string
  responses: string[]
  evidence: string[]
  notes: string
}

// Active Quest Types
export interface QuestProgress {
  id: string
  timestamp: string
  note: string
  evidence: string[]
}

export interface ActiveQuest {
  id: string
  questId?: string  // Reference to QUESTS array if it's a predefined quest
  title: string
  description: string
  instructions: string
  section: string
  subsection: string
  type: string
  tier: string
  image: string
  startedAt: string
  progressNotes: QuestProgress[]
}

// Helper functions
export function getAvatarStage(level: number) {
  for (let i = AVATAR_STAGES.length - 1; i >= 0; i--) {
    if (level >= AVATAR_STAGES[i].minLevel) return { ...AVATAR_STAGES[i], index: i }
  }
  return { ...AVATAR_STAGES[0], index: 0 }
}

export function getSubsection(sectionId: string, subsectionId: string) {
  const subs = SUBSECTIONS[sectionId]
  return subs?.find(s => s.id === subsectionId)
}

